name: Build Windows

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: windows
          target: desktop
          arch: win64_mingw81

      - name: Build
        shell: cmd
        run: |
          cd E34dash
          qmake E34dash.pro
          mingw32-make

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: E34dash
          path: |
            E34dash/**/*.exe
